### ISSUE TITLE
Just curious question

### ISSUE THREAD

**Issue by thepenguinthatwants** [nbeaver/stow-makefile#1]
Hi!

I just noticed that I am not the only one that controls stow with makefile. Tho I am wondering whats the difference with those?

```
stow: Makefile $(stow_dirs)
stow --target $(HOME) --verbose $(stow_dirs)
```

```
stow: 
stow --target $(HOME) --verbose $(stow_dirs)
```

seems like both ways works.

**Comment by nbeaver** [comment]
Good point, I switched them to [phony targets](https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html) so they always run. I'm not sure why I added those dependencies; I can't think of any situation where they would matter.
